### ISSUE TITLE
Please upload data

### ISSUE THREAD

**Issue by subercui** [yhr91/gears_misc#2]
Hi, thanks for sharing the reproducible notebooks for the paper. Could you please upload the data used in the notebooks to make them actually reproducible?

**Comment by kexinhuang12345** [comment]
Checkout this notebook: https://github.com/snap-stanford/GEARS/blob/master/demo/data_tutorial.ipynb

**Comment by woyaopaolula** [comment]
> Checkout this notebook: https://github.com/snap-stanford/GEARS/blob/master/demo/data_tutorial.ipynb查看此笔记本：https://github.com/snap-stanford/GEARS/blob/master/demo/data_tutorial.ipynb

thank you ! I love you
