### ISSUE TITLE
Reproduce figure 2 b-g

### ISSUE THREAD

**Issue by subercui** [yhr91/gears_misc#3]
Hi, could you provide code to reproduce figure 2b-g in your preprint? Or at least could tell how to rerun the analysis workflow?

![](https://www.biorxiv.org/content/biorxiv/early/2022/07/15/2022.07.12.499735/F2.large.jpg)

**Comment by kexinhuang12345** [comment]
https://github.com/snap-stanford/GEARS/issues/5
