### ISSUE TITLE
Reproduce figure 3

### ISSUE THREAD

**Issue by subercui** [yhr91/gears_misc#4]
Hi, I am trying to reproduce the analysis in figure 3, particularly the UMAPs. Could you let me know how to do it?

Some related questions:

1. Should I use the script https://github.com/yhr91/gears_misc/blob/main/paper/Fig3_UMAP_predict.py and https://github.com/yhr91/gears_misc/blob/main/paper/Fig3_UMAP_train.py?

2. It seems the `Fig3_UMAP_train.py` only saved the model, so how did you generate the embeddings used in figure 3b?

3. Similarly, what embedding vectors you used to generate figure 3c? Is it related to this line https://github.com/yhr91/gears_misc/blob/73a026049d22107ef1a31c81cb677f646b62dea1/paper/Fig3_UMAP_predict.py#L69

Thank you!

**Comment by yhr91** [comment]
Sorry for the late reply, wasn't notified about this issue.

1. Yes, those were the scripts used to produce the results

2. I've added [the notebook](https://github.com/yhr91/gears_misc/blob/main/paper/figure3.ipynb) to this repository that was used to generate figure 3

3. Yes, we used `model_name+'_all_preds'` to make the UMAP
