### ISSUE TITLE
Publication of model parameters

### ISSUE THREAD

**Issue by fratajcz** [yhr91/gears_misc#6]
Hi!

I have posted an issue in the snap-stanford github repo of the final GEARS model. Since I didn't know which repo is more likely to catch your attention, I simply want to link it here: https://github.com/snap-stanford/GEARS/issues/50 . Feel free to answer in any one of the two repos.

Thank you for your time.

**Comment by yhr91** [comment]
https://github.com/snap-stanford/GEARS/issues/50
